# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

jobs:
  # build:
  #   docker:
  #     - image: circleci/node:16.13.0-browsers
  test:
    docker:
      - image: circleci/node:16.13.0-browsers
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: 'npm install'
      # - run:
      #     name: "Start Development Server"
      #     command: 'npm run start-server:dev'
      #     background: true
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      # - run:
      #     name: Build images of services declared in docker-compose.yml
      #     command: docker-compose build
      - run:
          name: 'Unit Testing'
          # Use Double Quotes for yaml parser to not be confused w/ colons:
          command: 'npm run test:ci:unit'
      - run:
          name: 'Compose Up'
          command: 'docker-compose -f ./docker/docker-compose.yml up'
          background: true
      - run:
          name: 'Blackbox Testing'
          command: 'npm run test:ci:blackbox'
      - run:
          name: 'Coverage Summary'
          command: 'npm run test:ci:summary'


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      # - node/test:
      #     # This is the node version to use for the `cimg/node` tag
      #     # Relevant tags can be found on the CircleCI Developer Hub
      #     # https://circleci.com/developer/images/image/cimg/node
      #     version: '16.13'
      #     # If you are using yarn, change the line below from "npm" to "yarn"
      #     pkg-manager: npm
      # - build
      - test