version: '3.7'

services:
  mongodb:
    image: mongo:5.0.7
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: testdb
    ports:
      - 27017:27017
    command: ["--bind_ip_all"]